public class ForEachLoopDemo1 {
    public static void iterateIntegerList() {
        List<Integer> listInteger = new List<Integer>();
            listInteger.add(10); //index = 0 (index=order)
            listInteger.add(15); //index = 1 
            listInteger.add(21); //index = 2 
            listInteger.add(15); //index = 3

            for (integer eachInteger : listInteger) {
                    system.debug(eachInteger);
            }

    }
}
